import static org.junit.Assert.*;
import com.oocourse.spec3.exceptions.EqualPersonIdException;
import com.oocourse.spec3.main.Message;
import com.oocourse.spec3.main.Person;

public class MyNetworkTest {
    MyNetwork network = new MyNetwork();
    MyNetwork network1 = new MyNetwork();
    @org.junit.Test
    public void deleteColdEmoji() {
        try {
            network.addPerson(new MyPerson(1, "aa", 10));
            network.addPerson(new MyPerson(2, "bb", 20));
            network.addPerson(new MyPerson(3, "cc", 30));
            network.addPerson(new MyPerson(4, "dd", 40));
            network.addPerson(new MyPerson(5, "ee", 50));
            network.addPerson(new MyPerson(6, "ff", 60));
            network.addPerson(new MyPerson(7, "gg", 70));
            network.addPerson(new MyPerson(8, "hh", 80));
            network.addPerson(new MyPerson(9, "ii", 90));
            network.addPerson(new MyPerson(10, "jj", 100));
            network.addPerson(new MyPerson(11, "kk", 110));
            network.addPerson(new MyPerson(12, "ll", 120));
            network.addPerson(new MyPerson(13, "aa", 10));
            network.addPerson(new MyPerson(14, "bb", 20));
            network.addPerson(new MyPerson(15, "cc", 30));

            network1.addPerson(new MyPerson(1, "aa", 10));
            network1.addPerson(new MyPerson(2, "bb", 20));
            network1.addPerson(new MyPerson(3, "cc", 30));
            network1.addPerson(new MyPerson(4, "dd", 40));
            network1.addPerson(new MyPerson(5, "ee", 50));
            network1.addPerson(new MyPerson(6, "ff", 60));
            network1.addPerson(new MyPerson(7, "gg", 70));
            network1.addPerson(new MyPerson(8, "hh", 80));
            network1.addPerson(new MyPerson(9, "ii", 90));
            network1.addPerson(new MyPerson(10, "jj", 100));
            network1.addPerson(new MyPerson(11, "kk", 110));
            network1.addPerson(new MyPerson(12, "ll", 120));
            network1.addPerson(new MyPerson(13, "aa", 10));
            network1.addPerson(new MyPerson(14, "bb", 20));
            network1.addPerson(new MyPerson(15, "cc", 30));
        } catch (EqualPersonIdException e) {
            throw new RuntimeException(e);
        }

        for (int i = 1; i < 14; i++) {
            MyTag tag = new MyTag(1);
            MyTag tag1 = new MyTag(1);
            try {
                network.addTag(i,tag);
                network1.addTag(i,tag1);
                network.addPersonToTag(15,i,1);
                network1.addPersonToTag(15,i,1);
            } catch (Exception e) {
                System.out.println();
            }
            try {
                network.storeEmojiId(i);
                network1.storeEmojiId(i);
            } catch (Exception e) {
                System.out.println();
            }
        }
        try {            network.addRelation(4, 6, -751); network1.addRelation(4, 6, -751);        } catch (Exception e) {            System.out.println();        }
        try {            network.addRelation(2, 6, -175); network1.addRelation(2, 6, -175);        } catch (Exception e) {            System.out.println();        }
        try {            network.addRelation(6, 2, -686); network1.addRelation(6, 2, -686);        } catch (Exception e) {            System.out.println();        }
        try {            network.addRelation(13, 9, -978); network1.addRelation(13, 9, -978);        } catch (Exception e) {            System.out.println();        }
        try {            network.addRelation(5, 13, -499); network1.addRelation(5, 13, -499);        } catch (Exception e) {            System.out.println();        }
        try {            network.addRelation(10, 6, -595); network1.addRelation(10, 6, -595);        } catch (Exception e) {            System.out.println();        }
        try {            network.addRelation(10, 2, -189); network1.addRelation(10, 2, -189);        } catch (Exception e) {            System.out.println();        }
        try {            network.addRelation(7, 12, -908); network1.addRelation(7, 12, -908);        } catch (Exception e) {            System.out.println();        }
        try {            network.addRelation(12, 9, -957); network1.addRelation(12, 9, -957);        } catch (Exception e) {            System.out.println();        }
        try {            network.addRelation(11, 14, -7); network1.addRelation(11, 14, -7);        } catch (Exception e) {            System.out.println();        }



        try {            MyMessage temMessage1 = new MyMessage(268,276,network.getPerson(7), network.getPerson(15));            MyMessage temMessage2 = new MyMessage(268,276,network1.getPerson(7), network1.getPerson(15));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(115,115,network.getPerson(11), network.getPerson(9));            MyMessage temMessage2 = new MyMessage(115,115,network1.getPerson(11), network1.getPerson(9));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(130,189,network.getPerson(4), network.getPerson(6));            MyMessage temMessage2 = new MyMessage(130,189,network1.getPerson(4), network1.getPerson(6));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(46,45,network.getPerson(12), network.getPerson(2));            MyMessage temMessage2 = new MyMessage(46,45,network1.getPerson(12), network1.getPerson(2));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(214,92,network.getPerson(14), network.getPerson(3));            MyMessage temMessage2 = new MyMessage(214,92,network1.getPerson(14), network1.getPerson(3));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(278,205,network.getPerson(3), network.getPerson(4));            MyMessage temMessage2 = new MyMessage(278,205,network1.getPerson(3), network1.getPerson(4));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(134,86,network.getPerson(6), network.getPerson(4));            MyMessage temMessage2 = new MyMessage(134,86,network1.getPerson(6), network1.getPerson(4));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(207,209,network.getPerson(9), network.getPerson(15));            MyMessage temMessage2 = new MyMessage(207,209,network1.getPerson(9), network1.getPerson(15));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(240,159,network.getPerson(7), network.getPerson(11));
            MyMessage temMessage2 = new MyMessage(240,159,network1.getPerson(7), network1.getPerson(11));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(195,236,network.getPerson(6), network.getPerson(3));            MyMessage temMessage2 = new MyMessage(195,236,network1.getPerson(6), network1.getPerson(3));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(117,87,network.getPerson(3), network.getPerson(9));            MyMessage temMessage2 = new MyMessage(117,87,network1.getPerson(3), network1.getPerson(9));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(287,217,network.getPerson(13), network.getPerson(1));
            MyMessage temMessage2 = new MyMessage(287,217,network1.getPerson(13), network1.getPerson(1));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(119,236,network.getPerson(6), network.getPerson(6));            MyMessage temMessage2 = new MyMessage(119,236,network1.getPerson(6), network1.getPerson(6));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(154,236,network.getPerson(1), network.getPerson(1));            MyMessage temMessage2 = new MyMessage(154,236,network1.getPerson(1), network1.getPerson(1));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(123,266,network.getPerson(9), network.getPerson(9));            MyMessage temMessage2 = new MyMessage(123,266,network1.getPerson(9), network1.getPerson(9));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(28,175,network.getPerson(8), network.getPerson(4));            MyMessage temMessage2 = new MyMessage(28,175,network1.getPerson(8), network1.getPerson(4));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(188,255,network.getPerson(12), network.getPerson(14));
            MyMessage temMessage2 = new MyMessage(188,255,network1.getPerson(12), network1.getPerson(14));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(85,142,network.getPerson(9), network.getPerson(9));            MyMessage temMessage2 = new MyMessage(85,142,network1.getPerson(9), network1.getPerson(9));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(202,55,network.getPerson(3), network.getPerson(14));            MyMessage temMessage2 = new MyMessage(202,55,network1.getPerson(3), network1.getPerson(14));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(187,275,network.getPerson(11), network.getPerson(6));
            MyMessage temMessage2 = new MyMessage(187,275,network1.getPerson(11), network1.getPerson(6));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(228,84,network.getPerson(14), network.getPerson(13));
            MyMessage temMessage2 = new MyMessage(228,84,network1.getPerson(14), network1.getPerson(13));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(71,63,network.getPerson(2), network.getPerson(5));            MyMessage temMessage2 = new MyMessage(71,63,network1.getPerson(2), network1.getPerson(5));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(50,203,network.getPerson(3), network.getPerson(3));            MyMessage temMessage2 = new MyMessage(50,203,network1.getPerson(3), network1.getPerson(3));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(13,300,network.getPerson(6), network.getPerson(6));            MyMessage temMessage2 = new MyMessage(13,300,network1.getPerson(6), network1.getPerson(6));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(239,66,network.getPerson(4), network.getPerson(8));            MyMessage temMessage2 = new MyMessage(239,66,network1.getPerson(4), network1.getPerson(8));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(299,273,network.getPerson(5), network.getPerson(2));            MyMessage temMessage2 = new MyMessage(299,273,network1.getPerson(5), network1.getPerson(2));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(61,148,network.getPerson(15), network.getPerson(15));
            MyMessage temMessage2 = new MyMessage(61,148,network1.getPerson(15), network1.getPerson(15));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(26,140,network.getPerson(1), network.getPerson(15));            MyMessage temMessage2 = new MyMessage(26,140,network1.getPerson(1), network1.getPerson(15));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(128,200,network.getPerson(10), network.getPerson(9));
            MyMessage temMessage2 = new MyMessage(128,200,network1.getPerson(10), network1.getPerson(9));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(30,12,network.getPerson(9), network.getPerson(8));            MyMessage temMessage2 = new MyMessage(30,12,network1.getPerson(9), network1.getPerson(8));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(67,66,network.getPerson(12), network.getPerson(3));            MyMessage temMessage2 = new MyMessage(67,66,network1.getPerson(12), network1.getPerson(3));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(137,39,network.getPerson(10), network.getPerson(7));            MyMessage temMessage2 = new MyMessage(137,39,network1.getPerson(10), network1.getPerson(7));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(207,85,network.getPerson(15), network.getPerson(9));            MyMessage temMessage2 = new MyMessage(207,85,network1.getPerson(15), network1.getPerson(9));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(187,72,network.getPerson(8), network.getPerson(13));            MyMessage temMessage2 = new MyMessage(187,72,network1.getPerson(8), network1.getPerson(13));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(90,211,network.getPerson(9), network.getPerson(3));            MyMessage temMessage2 = new MyMessage(90,211,network1.getPerson(9), network1.getPerson(3));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(49,5,network.getPerson(10), network.getPerson(14));            MyMessage temMessage2 = new MyMessage(49,5,network1.getPerson(10), network1.getPerson(14));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(21,36,network.getPerson(5), network.getPerson(2));            MyMessage temMessage2 = new MyMessage(21,36,network1.getPerson(5), network1.getPerson(2));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(129,9,network.getPerson(15), network.getPerson(7));            MyMessage temMessage2 = new MyMessage(129,9,network1.getPerson(15), network1.getPerson(7));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(146,72,network.getPerson(10), network.getPerson(12));
            MyMessage temMessage2 = new MyMessage(146,72,network1.getPerson(10), network1.getPerson(12));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(11,186,network.getPerson(3), network.getPerson(8));            MyMessage temMessage2 = new MyMessage(11,186,network1.getPerson(3), network1.getPerson(8));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(283,292,network.getPerson(3), network.getPerson(2));            MyMessage temMessage2 = new MyMessage(283,292,network1.getPerson(3), network1.getPerson(2));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(164,21,network.getPerson(3), network.getPerson(2));            MyMessage temMessage2 = new MyMessage(164,21,network1.getPerson(3), network1.getPerson(2));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(165,272,network.getPerson(13), network.getPerson(8));
            MyMessage temMessage2 = new MyMessage(165,272,network1.getPerson(13), network1.getPerson(8));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(298,59,network.getPerson(2), network.getPerson(15));            MyMessage temMessage2 = new MyMessage(298,59,network1.getPerson(2), network1.getPerson(15));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(226,100,network.getPerson(11), network.getPerson(12));
            MyMessage temMessage2 = new MyMessage(226,100,network1.getPerson(11), network1.getPerson(12));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(65,22,network.getPerson(7), network.getPerson(14));            MyMessage temMessage2 = new MyMessage(65,22,network1.getPerson(7), network1.getPerson(14));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(67,263,network.getPerson(14), network.getPerson(10));
            MyMessage temMessage2 = new MyMessage(67,263,network1.getPerson(14), network1.getPerson(10));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(181,167,network.getPerson(4), network.getPerson(3));            MyMessage temMessage2 = new MyMessage(181,167,network1.getPerson(4), network1.getPerson(3));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(43,18,network.getPerson(9), network.getPerson(8));            MyMessage temMessage2 = new MyMessage(43,18,network1.getPerson(9), network1.getPerson(8));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyMessage temMessage1 = new MyMessage(77,202,network.getPerson(5), network.getPerson(14));            MyMessage temMessage2 = new MyMessage(77,202,network1.getPerson(5), network1.getPerson(14));               network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }







        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(90,91, network.getPerson(5), network.getPerson(2) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(90,91, network1.getPerson(5), network1.getPerson(2) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(90);            network1.sendMessage(90);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(184,11, network.getPerson(13), network.getPerson(10) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(184,11, network1.getPerson(13), network1.getPerson(10) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(184);            network1.sendMessage(184);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(193,263, network.getPerson(1), network.getPerson(13) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(193,263, network1.getPerson(1), network1.getPerson(13) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(193);            network1.sendMessage(193);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(161,211, network.getPerson(9), network.getPerson(2) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(161,211, network1.getPerson(9), network1.getPerson(2) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(161);            network1.sendMessage(161);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(28,177, network.getPerson(5), network.getPerson(3) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(28,177, network1.getPerson(5), network1.getPerson(3) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(28);            network1.sendMessage(28);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(245,139, network.getPerson(5), network.getPerson(2) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(245,139, network1.getPerson(5), network1.getPerson(2) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(245);            network1.sendMessage(245);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(259,156, network.getPerson(14), network.getPerson(3) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(259,156, network1.getPerson(14), network1.getPerson(3) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(259);            network1.sendMessage(259);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(219,18, network.getPerson(7), network.getPerson(12) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(219,18, network1.getPerson(7), network1.getPerson(12) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(219);            network1.sendMessage(219);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(125,228, network.getPerson(7), network.getPerson(5) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(125,228, network1.getPerson(7), network1.getPerson(5) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(125);            network1.sendMessage(125);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(58,52, network.getPerson(3), network.getPerson(1) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(58,52, network1.getPerson(3), network1.getPerson(1) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(58);            network1.sendMessage(58);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(144,37, network.getPerson(4), network.getPerson(14) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(144,37, network1.getPerson(4), network1.getPerson(14) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(144);            network1.sendMessage(144);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(239,100, network.getPerson(1), network.getPerson(4) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(239,100, network1.getPerson(1), network1.getPerson(4) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(239);            network1.sendMessage(239);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(49,232, network.getPerson(6), network.getPerson(11) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(49,232, network1.getPerson(6), network1.getPerson(11) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(49);            network1.sendMessage(49);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(285,69, network.getPerson(3), network.getPerson(1) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(285,69, network1.getPerson(3), network1.getPerson(1) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(285);            network1.sendMessage(285);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(174,230, network.getPerson(12), network.getPerson(4) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(174,230, network1.getPerson(12), network1.getPerson(4) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(174);            network1.sendMessage(174);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(152,25, network.getPerson(9), network.getPerson(3) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(152,25, network1.getPerson(9), network1.getPerson(3) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(152);            network1.sendMessage(152);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(53,63, network.getPerson(3), network.getPerson(2) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(53,63, network1.getPerson(3), network1.getPerson(2) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(53);            network1.sendMessage(53);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(42,231, network.getPerson(3), network.getPerson(7) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(42,231, network1.getPerson(3), network1.getPerson(7) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(42);            network1.sendMessage(42);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(168,268, network.getPerson(3), network.getPerson(4) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(168,268, network1.getPerson(3), network1.getPerson(4) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(168);            network1.sendMessage(168);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(247,207, network.getPerson(13), network.getPerson(2) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(247,207, network1.getPerson(13), network1.getPerson(2) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(247);            network1.sendMessage(247);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(135,293, network.getPerson(10), network.getPerson(10) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(135,293, network1.getPerson(10), network1.getPerson(10) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(135);            network1.sendMessage(135);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(84,285, network.getPerson(4), network.getPerson(1) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(84,285, network1.getPerson(4), network1.getPerson(1) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(84);            network1.sendMessage(84);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(76,77, network.getPerson(5), network.getPerson(12) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(76,77, network1.getPerson(5), network1.getPerson(12) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(76);            network1.sendMessage(76);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(3,46, network.getPerson(11), network.getPerson(5) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(3,46, network1.getPerson(11), network1.getPerson(5) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(3);            network1.sendMessage(3);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(300,109, network.getPerson(3), network.getPerson(10) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(300,109, network1.getPerson(3), network1.getPerson(10) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(300);            network1.sendMessage(300);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(241,87, network.getPerson(3), network.getPerson(14) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(241,87, network1.getPerson(3), network1.getPerson(14) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(241);            network1.sendMessage(241);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(199,176, network.getPerson(14), network.getPerson(1) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(199,176, network1.getPerson(14), network1.getPerson(1) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(199);            network1.sendMessage(199);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(159,84, network.getPerson(5), network.getPerson(12) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(159,84, network1.getPerson(5), network1.getPerson(12) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(159);            network1.sendMessage(159);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(155,113, network.getPerson(1), network.getPerson(14) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(155,113, network1.getPerson(1), network1.getPerson(14) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(155);            network1.sendMessage(155);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(181,121, network.getPerson(13), network.getPerson(5) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(181,121, network1.getPerson(13), network1.getPerson(5) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(181);            network1.sendMessage(181);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(293,236, network.getPerson(5), network.getPerson(6) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(293,236, network1.getPerson(5), network1.getPerson(6) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(293);            network1.sendMessage(293);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(66,145, network.getPerson(4), network.getPerson(10) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(66,145, network1.getPerson(4), network1.getPerson(10) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(66);            network1.sendMessage(66);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(12,285, network.getPerson(10), network.getPerson(9) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(12,285, network1.getPerson(10), network1.getPerson(9) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(12);            network1.sendMessage(12);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(267,14, network.getPerson(11), network.getPerson(1) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(267,14, network1.getPerson(11), network1.getPerson(1) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(267);            network1.sendMessage(267);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(193,284, network.getPerson(4), network.getPerson(15) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(193,284, network1.getPerson(4), network1.getPerson(15) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(193);            network1.sendMessage(193);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(291,114, network.getPerson(12), network.getPerson(8) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(291,114, network1.getPerson(12), network1.getPerson(8) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(291);            network1.sendMessage(291);        } catch (Exception e){            System.out.println();        }
        try {            MyEmojiMessage temMessage1 = new MyEmojiMessage(201,80, network.getPerson(8), network.getPerson(15) );             MyEmojiMessage temMessage2 = new MyEmojiMessage(201,80, network1.getPerson(8), network1.getPerson(15) );  network.addMessage(temMessage1);                       network1.addMessage(temMessage2);            network.sendMessage(201);            network1.sendMessage(201);        } catch (Exception e){            System.out.println();        }




        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(227,13, network.getPerson(1), network.getPerson(2));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(227,13, network1.getPerson(1), network1.getPerson(2));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(97,104, network.getPerson(8), network.getPerson(7));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(97,104, network1.getPerson(8), network1.getPerson(7));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(102,152, network.getPerson(9), network.getPerson(11));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(102,152, network1.getPerson(9), network1.getPerson(11));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(119,220, network.getPerson(9), network.getPerson(6));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(119,220, network1.getPerson(9), network1.getPerson(6));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(134,200, network.getPerson(14), network.getPerson(14));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(134,200, network1.getPerson(14), network1.getPerson(14));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(4,157, network.getPerson(12), network.getPerson(15));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(4,157, network1.getPerson(12), network1.getPerson(15));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(218,73, network.getPerson(11), network.getPerson(8));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(218,73, network1.getPerson(11), network1.getPerson(8));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(127,288, network.getPerson(12), network.getPerson(6));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(127,288, network1.getPerson(12), network1.getPerson(6));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(80,115, network.getPerson(5), network.getPerson(13));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(80,115, network1.getPerson(5), network1.getPerson(13));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(38,84, network.getPerson(15), network.getPerson(12));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(38,84, network1.getPerson(15), network1.getPerson(12));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(86,158, network.getPerson(15), network.getPerson(15));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(86,158, network1.getPerson(15), network1.getPerson(15));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(47,39, network.getPerson(9), network.getPerson(14));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(47,39, network1.getPerson(9), network1.getPerson(14));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(261,243, network.getPerson(11), network.getPerson(7));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(261,243, network1.getPerson(11), network1.getPerson(7));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(98,270, network.getPerson(1), network.getPerson(5));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(98,270, network1.getPerson(1), network1.getPerson(5));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(185,109, network.getPerson(8), network.getPerson(2));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(185,109, network1.getPerson(8), network1.getPerson(2));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(240,277, network.getPerson(14), network.getPerson(4));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(240,277, network1.getPerson(14), network1.getPerson(4));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(182,201, network.getPerson(15), network.getPerson(15));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(182,201, network1.getPerson(15), network1.getPerson(15));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(198,193, network.getPerson(9), network.getPerson(14));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(198,193, network1.getPerson(9), network1.getPerson(14));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(263,91, network.getPerson(6), network.getPerson(8));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(263,91, network1.getPerson(6), network1.getPerson(8));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(136,268, network.getPerson(13), network.getPerson(15));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(136,268, network1.getPerson(13), network1.getPerson(15));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(142,202, network.getPerson(10), network.getPerson(11));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(142,202, network1.getPerson(10), network1.getPerson(11));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(215,117, network.getPerson(3), network.getPerson(3));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(215,117, network1.getPerson(3), network1.getPerson(3));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(9,96, network.getPerson(13), network.getPerson(2));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(9,96, network1.getPerson(13), network1.getPerson(2));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(16,225, network.getPerson(4), network.getPerson(8));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(16,225, network1.getPerson(4), network1.getPerson(8));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(204,120, network.getPerson(14), network.getPerson(13));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(204,120, network1.getPerson(14), network1.getPerson(13));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(258,24, network.getPerson(10), network.getPerson(10));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(258,24, network1.getPerson(10), network1.getPerson(10));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(208,278, network.getPerson(11), network.getPerson(2));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(208,278, network1.getPerson(11), network1.getPerson(2));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(152,113, network.getPerson(12), network.getPerson(6));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(152,113, network1.getPerson(12), network1.getPerson(6));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(49,282, network.getPerson(6), network.getPerson(15));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(49,282, network1.getPerson(6), network1.getPerson(15));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(228,37, network.getPerson(6), network.getPerson(9));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(228,37, network1.getPerson(6), network1.getPerson(9));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(150,273, network.getPerson(3), network.getPerson(3));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(150,273, network1.getPerson(3), network1.getPerson(3));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(261,201, network.getPerson(7), network.getPerson(7));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(261,201, network1.getPerson(7), network1.getPerson(7));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(188,198, network.getPerson(4), network.getPerson(14));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(188,198, network1.getPerson(4), network1.getPerson(14));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(186,227, network.getPerson(12), network.getPerson(12));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(186,227, network1.getPerson(12), network1.getPerson(12));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(106,299, network.getPerson(10), network.getPerson(12));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(106,299, network1.getPerson(10), network1.getPerson(12));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(212,70, network.getPerson(3), network.getPerson(12));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(212,70, network1.getPerson(3), network1.getPerson(12));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(32,130, network.getPerson(12), network.getPerson(3));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(32,130, network1.getPerson(12), network1.getPerson(3));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(36,299, network.getPerson(5), network.getPerson(11));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(36,299, network1.getPerson(5), network1.getPerson(11));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(79,52, network.getPerson(7), network.getPerson(7));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(79,52, network1.getPerson(7), network1.getPerson(7));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(107,132, network.getPerson(15), network.getPerson(2));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(107,132, network1.getPerson(15), network1.getPerson(2));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(118,209, network.getPerson(2), network.getPerson(11));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(118,209, network1.getPerson(2), network1.getPerson(11));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(73,21, network.getPerson(9), network.getPerson(2));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(73,21, network1.getPerson(9), network1.getPerson(2));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(13,38, network.getPerson(14), network.getPerson(5));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(13,38, network1.getPerson(14), network1.getPerson(5));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(262,166, network.getPerson(6), network.getPerson(11));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(262,166, network1.getPerson(6), network1.getPerson(11));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(76,10, network.getPerson(14), network.getPerson(7));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(76,10, network1.getPerson(14), network1.getPerson(7));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(292,294, network.getPerson(14), network.getPerson(12));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(292,294, network1.getPerson(14), network1.getPerson(12));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(204,130, network.getPerson(12), network.getPerson(10));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(204,130, network1.getPerson(12), network1.getPerson(10));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(147,107, network.getPerson(6), network.getPerson(5));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(147,107, network1.getPerson(6), network1.getPerson(5));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(219,37, network.getPerson(14), network.getPerson(3));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(219,37, network1.getPerson(14), network1.getPerson(3));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(204,143, network.getPerson(7), network.getPerson(8));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(204,143, network1.getPerson(7), network1.getPerson(8));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyRedEnvelopeMessage temMessage1 = new MyRedEnvelopeMessage(223,64, network.getPerson(11), network.getPerson(6));            MyRedEnvelopeMessage temMessage2 = new MyRedEnvelopeMessage(223,64, network1.getPerson(11), network1.getPerson(6));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }



        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(118,"aa ", network.getPerson(4), network.getPerson(10));            MyNoticeMessage temMessage2 = new MyNoticeMessage(118,"aa ", network1.getPerson(4), network1.getPerson(10));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(156,"aa ", network.getPerson(7), network.getPerson(8));            MyNoticeMessage temMessage2 = new MyNoticeMessage(156,"aa ", network1.getPerson(7), network1.getPerson(8));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(11,"aa ", network.getPerson(14), network.getPerson(13));            MyNoticeMessage temMessage2 = new MyNoticeMessage(11,"aa ", network1.getPerson(14), network1.getPerson(13));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(43,"aa ", network.getPerson(10), network.getPerson(5));            MyNoticeMessage temMessage2 = new MyNoticeMessage(43,"aa ", network1.getPerson(10), network1.getPerson(5));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(225,"aa ", network.getPerson(9), network.getPerson(7));            MyNoticeMessage temMessage2 = new MyNoticeMessage(225,"aa ", network1.getPerson(9), network1.getPerson(7));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(77,"aa ", network.getPerson(12), network.getPerson(2));            MyNoticeMessage temMessage2 = new MyNoticeMessage(77,"aa ", network1.getPerson(12), network1.getPerson(2));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(294,"aa ", network.getPerson(6), network.getPerson(3));            MyNoticeMessage temMessage2 = new MyNoticeMessage(294,"aa ", network1.getPerson(6), network1.getPerson(3));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(192,"aa ", network.getPerson(4), network.getPerson(5));            MyNoticeMessage temMessage2 = new MyNoticeMessage(192,"aa ", network1.getPerson(4), network1.getPerson(5));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(254,"aa ", network.getPerson(11), network.getPerson(15));            MyNoticeMessage temMessage2 = new MyNoticeMessage(254,"aa ", network1.getPerson(11), network1.getPerson(15));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(9,"aa ", network.getPerson(10), network.getPerson(2));            MyNoticeMessage temMessage2 = new MyNoticeMessage(9,"aa ", network1.getPerson(10), network1.getPerson(2));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(197,"aa ", network.getPerson(1), network.getPerson(10));            MyNoticeMessage temMessage2 = new MyNoticeMessage(197,"aa ", network1.getPerson(1), network1.getPerson(10));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(230,"aa ", network.getPerson(9), network.getPerson(8));            MyNoticeMessage temMessage2 = new MyNoticeMessage(230,"aa ", network1.getPerson(9), network1.getPerson(8));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(158,"aa ", network.getPerson(7), network.getPerson(13));            MyNoticeMessage temMessage2 = new MyNoticeMessage(158,"aa ", network1.getPerson(7), network1.getPerson(13));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(190,"aa ", network.getPerson(4), network.getPerson(5));            MyNoticeMessage temMessage2 = new MyNoticeMessage(190,"aa ", network1.getPerson(4), network1.getPerson(5));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(134,"aa ", network.getPerson(5), network.getPerson(2));            MyNoticeMessage temMessage2 = new MyNoticeMessage(134,"aa ", network1.getPerson(5), network1.getPerson(2));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(196,"aa ", network.getPerson(15), network.getPerson(8));            MyNoticeMessage temMessage2 = new MyNoticeMessage(196,"aa ", network1.getPerson(15), network1.getPerson(8));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(251,"aa ", network.getPerson(8), network.getPerson(9));            MyNoticeMessage temMessage2 = new MyNoticeMessage(251,"aa ", network1.getPerson(8), network1.getPerson(9));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(244,"aa ", network.getPerson(7), network.getPerson(6));            MyNoticeMessage temMessage2 = new MyNoticeMessage(244,"aa ", network1.getPerson(7), network1.getPerson(6));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(113,"aa ", network.getPerson(15), network.getPerson(12));            MyNoticeMessage temMessage2 = new MyNoticeMessage(113,"aa ", network1.getPerson(15), network1.getPerson(12));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(18,"aa ", network.getPerson(1), network.getPerson(13));            MyNoticeMessage temMessage2 = new MyNoticeMessage(18,"aa ", network1.getPerson(1), network1.getPerson(13));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(5,"aa ", network.getPerson(9), network.getPerson(4));            MyNoticeMessage temMessage2 = new MyNoticeMessage(5,"aa ", network1.getPerson(9), network1.getPerson(4));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(57,"aa ", network.getPerson(4), network.getPerson(10));            MyNoticeMessage temMessage2 = new MyNoticeMessage(57,"aa ", network1.getPerson(4), network1.getPerson(10));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(149,"aa ", network.getPerson(8), network.getPerson(7));            MyNoticeMessage temMessage2 = new MyNoticeMessage(149,"aa ", network1.getPerson(8), network1.getPerson(7));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(21,"aa ", network.getPerson(13), network.getPerson(10));            MyNoticeMessage temMessage2 = new MyNoticeMessage(21,"aa ", network1.getPerson(13), network1.getPerson(10));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(109,"aa ", network.getPerson(11), network.getPerson(15));            MyNoticeMessage temMessage2 = new MyNoticeMessage(109,"aa ", network1.getPerson(11), network1.getPerson(15));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(17,"aa ", network.getPerson(7), network.getPerson(8));            MyNoticeMessage temMessage2 = new MyNoticeMessage(17,"aa ", network1.getPerson(7), network1.getPerson(8));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }
        try {            MyNoticeMessage temMessage1 = new MyNoticeMessage(241,"aa ", network.getPerson(11), network.getPerson(8));            MyNoticeMessage temMessage2 = new MyNoticeMessage(241,"aa ", network1.getPerson(11), network1.getPerson(8));            network.addMessage(temMessage1);            network1.addMessage(temMessage2);        } catch (Exception e){            System.out.println();        }


        Message[] temMessages1 = network.getMessages();
        int[] temEmojiIdList1 = network.getEmojiIdList();
        int[] temEmojiHeatList1 = network.getEmojiHeatList();
        int temSize = temEmojiIdList1.length;
        int max = 0;
        int min = Integer.MAX_VALUE;
        for (int i = 0; i < temEmojiHeatList1.length; i++) {
            if (temEmojiHeatList1[i] > max){
                max = temEmojiHeatList1[i];
            }
            if (temEmojiHeatList1[i] < min){
                min = temEmojiHeatList1[i];
            }
        }
        int limit = (max + min)/2;
        int[] temEmojiIdList2 = new int[temSize];
        int[] temEmojiHeatList2 = new int[temSize];
        Message[] temMessages2 = new Message[temMessages1.length];
        int j = 0;
        for (int i = 0; i < temEmojiHeatList1.length; i++) {
            if (temEmojiHeatList1[i] >= limit){
                temEmojiIdList2[j] = temEmojiIdList1[i];
                temEmojiHeatList2[j] = temEmojiHeatList1[i];
                j++;
            }
        }
        int backSize = j;
        j = 0;
        for (int i = 0; i < temMessages1.length; i++) {
            if (temMessages1[i] instanceof MyEmojiMessage){
                if (network.containsEmojiId(((MyEmojiMessage) temMessages1[i]).getEmojiId())){
                    temMessages2[j] = temMessages1[i];
                    j++;
                }
            }else {
                temMessages2[j] = temMessages1[i];
                j++;
            }
        }
        int result = network1.deleteColdEmoji(limit);
        assertEquals(backSize,result);
        int[] temEmojiIdList3 = network1.getEmojiIdList();
        int[] temEmojiHeatList3 = network1.getEmojiHeatList();
        Message[] temMessages3 = network1.getMessages();
        assertEquals(temMessages2.length,temMessages3.length);
        int flag1 = 0;
        int flag2 = 0;
        int flag3 = 0;
        for (int i = 0; i < temEmojiIdList3.length; i++) {
            int mark = 0;
            for (int k = 0; k < temEmojiIdList2.length; k++) {
                if (temEmojiIdList3[i] == temEmojiIdList2[k]){
                    mark = 1;
                    break;
                }
            }
            if (mark == 0){
                flag1 = 1;
                break;
            }
        }
        for (int i = 0; i < temEmojiHeatList3.length; i++) {
            int mark = 0;
            for (int k = 0; k < temEmojiHeatList2.length; k++) {
                if (temEmojiHeatList3[i] == temEmojiHeatList2[k]){
                    mark = 1;
                    break;
                }
            }
            if (mark == 0){
                flag2 = 1;
                break;
            }
        }
        for (int i = 0; i < temMessages3.length; i++) {
            int mark = 0;
            for (int k = 0; k < temMessages2.length; k++) {
                if (temMessages3[i].getId() == temMessages2[k].getId()){
                    mark = 1;
                    break;
                }
            }
            if (mark == 0){
                flag3 = 1;
                break;
            }
        }
        assertEquals(flag1,0);
        assertEquals(flag2,0);
        assertEquals(flag3,0);
    }
}